"""empty message

Revision ID: 212667bd223
Revises: 7bd4346fbc
Create Date: 2015-11-06 15:16:54.900751

"""

# revision identifiers, used by Alembic.
revision = '212667bd223'
down_revision = '7bd4346fbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
