"""empty message

Revision ID: 359a110e662
Revises: 3755a4a2d43
Create Date: 2015-11-09 10:16:37.281084

"""

# revision identifiers, used by Alembic.
revision = '359a110e662'
down_revision = '3755a4a2d43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
