"""empty message

Revision ID: 37365b61af3
Revises: 54134292594
Create Date: 2015-11-12 16:31:19.756298

"""

# revision identifiers, used by Alembic.
revision = '37365b61af3'
down_revision = '54134292594'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
