"""empty message

Revision ID: 3755a4a2d43
Revises: c9362bccac
Create Date: 2015-11-09 09:34:23.536594

"""

# revision identifiers, used by Alembic.
revision = '3755a4a2d43'
down_revision = 'c9362bccac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
