"""empty message

Revision ID: 37c1886797f
Revises: 41df6951e75
Create Date: 2015-11-11 09:40:24.263342

"""

# revision identifiers, used by Alembic.
revision = '37c1886797f'
down_revision = '41df6951e75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
