"""empty message

Revision ID: 3f41403f81c
Revises: d6ad60692c
Create Date: 2015-11-10 08:59:46.189412

"""

# revision identifiers, used by Alembic.
revision = '3f41403f81c'
down_revision = 'd6ad60692c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
