"""empty message

Revision ID: 48372bd2563
Revises: 37365b61af3
Create Date: 2015-11-16 11:58:41.543603

"""

# revision identifiers, used by Alembic.
revision = '48372bd2563'
down_revision = '37365b61af3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
