"""empty message

Revision ID: 4b2190a2c42
Revises: 359a110e662
Create Date: 2015-11-09 10:43:28.219692

"""

# revision identifiers, used by Alembic.
revision = '4b2190a2c42'
down_revision = '359a110e662'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
