"""empty message

Revision ID: 54cf585c2c7
Revises: 4b2190a2c42
Create Date: 2015-11-09 11:04:49.799447

"""

# revision identifiers, used by Alembic.
revision = '54cf585c2c7'
down_revision = '4b2190a2c42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
