"""empty message

Revision ID: d6ad60692c
Revises: 32797d30d77
Create Date: 2015-11-09 15:46:00.313932

"""

# revision identifiers, used by Alembic.
revision = 'd6ad60692c'
down_revision = '32797d30d77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
